[build]
  command = "make build"
  publish = "build/"

[[redirects]]
  from = "http://buf.netlify.com/docs/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.app/docs/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.com/docs/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.app/docs/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/introduction"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.com/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.app/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.com/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.app/introduction"
  to = "https://docs.buf.build/"
  status = 301
  force = true

[[redirects]]
  from = "/introduction"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.com/docs/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.app/docs/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.com/docs/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.app/docs/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.com/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://buf.netlify.app/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.com/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://buf.netlify.app/*"
  to = "https://docs.buf.build/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/lint-checkers"
  to = "/lint-rules"
  status = 301
  force = true

[[redirects]]
  from = "/breaking-checkers"
  to = "/breaking-rules"
  status = 301
  force = true

[[redirects]]
  from = "/breaking-configuration"
  to = "/breaking/configuration"
  status = 301
  force = true

[[redirects]]
  from = "/breaking-overview"
  to = "/breaking/overview"
  status = 301
  force = true

[[redirects]]
  from = "/breaking-protoc-plugin"
  to = "/breaking/protoc-plugin"
  status = 301
  force = true

[[redirects]]
  from = "/breaking-rules"
  to = "/breaking/rules"
  status = 301
  force = true

[[redirects]]
  from = "/breaking-usage"
  to = "/breaking/usage"
  status = 301
  force = true

[[redirects]]
  from = "/build-compiler"
  to = "/build/internal-compiler"
  status = 301
  force = true

[[redirects]]
  from = "/build-configuration"
  to = "/build/usage#configuration"
  status = 301
  force = true

[[redirects]]
  from = "/build-images"
  to = "/reference/images"
  status = 301
  force = true

[[redirects]]
  from = "/build-overview"
  to = "/build/usage"
  status = 301
  force = true

[[redirects]]
  from = "/configuration"
  to = "/configuration/overview"
  status = 301
  force = true

[[redirects]]
  from = "/generate-protoc"
  to = "/generate/overview"
  status = 301
  force = true

[[redirects]]
  from = "/generate-usage"
  to = "/generate/usage"
  status = 301
  force = true

[[redirects]]
  from = "/inputs"
  to = "/reference/inputs"
  status = 301
  force = true

[[redirects]]
  from = "/lint-configuration"
  to = "/lint/configuration"
  status = 301
  force = true

[[redirects]]
  from = "/lint-overview"
  to = "/lint/overview"
  status = 301
  force = true

[[redirects]]
  from = "/lint-protoc-plugin"
  to = "/lint/protoc-plugin"
  status = 301
  force = true

[[redirects]]
  from = "/lint-rules"
  to = "/lint/rules"
  status = 301
  force = true

[[redirects]]
  from = "/lint-usage"
  to = "/lint/usage"
  status = 301
  force = true

[[redirects]]
  from = "/migration-protolock"
  to = "/how-to/migrate-from-protolock"
  status = 301
  force = true

[[redirects]]
  from = "/migration-prototool"
  to = "/how-to/migrate-from-prototool"
  status = 301
  force = true

[[redirects]]
  from = "/style-guide"
  to = "/best-practices/style-guide"
  status = 301
  force = true

[[redirects]]
  from = "/grpc"
  to = "/how-to/grpc"
  status = 301
  force = true

# Not all of the steps in the previous tour have a matching step in the revised
# tour (e.g. "use the protoc lint and breaking plugins"). Plus, given that the
# steps in the tour can be reordered over time, referring to the nth step of the
# tour is unreliable. For this reason, all of the previously numbered tour steps
# should just redirect to the introduction.
[[redirects]]
  from = "/tour-*"
  to = "/tour/introduction"
  status = 301
  force = true

# Convenience redirects for intro pages.
[[redirects]]
  from = "/build"
  to = "/build/usage"
  status = 301

[[redirects]]
  from = "/generate"
  to = "/generate/usage"
  status = 301

[[redirects]]
  from = "/lint"
  to = "/lint/overview"
  status = 301

[[redirects]]
  from = "/breaking"
  to = "/breaking/overview"
  status = 301

[[redirects]]
  from = "/bsr"
  to = "/bsr/introduction"
  status = 301

[[redirects]]
  from = "/bsr/remote-generation"
  to = "/bsr/remote-generation/overview"
  status = 301

[[redirects]]
  from = "/best-practices"
  to = "/best-practices/style-guide"
  status = 301

[[redirects]]
  from = "/ci-cd"
  to = "/ci-cd/setup"
  status = 301

[[redirects]]
  from = "/configuration"
  to = "/configuration/overview"
  status = 301

[[redirects]]
  from = "/generate/high-performance-protoc-replacement"
  to = "/generate/usage"
  status = 301

[[redirects]]
  from = "/tour"
  to = "/tour/introduction"
  status = 301

[[redirects]]
  from = "/build/internal-compiler"
  to = "/reference/internal-compiler"
  status = 301

[[redirects]]
  from = "/breaking/protoc-plugin"
  to = "/reference/protoc-plugins#breaking"
  status = 301

[[redirects]]
  from = "/lint/protoc-plugin"
  to = "/reference/protoc-plugins#lint"
  status = 301

# Corrects a prior misspelling
[[redirects]]
  from = "/tour/login-to-the-bsr"
  to = "/tour/log-into-the-bsr"
  status = 301

[[redirects]]
  from = "/bsr-npm"
  to = "/bsr/remote-generation/npm"
  status = 301
